apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
    http:
      paths:
        - backend:
            serviceName: {{ .Chart.Name }}
            servicePort: 80
          path: /
