apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    http:
      paths:
        - backend:
            serviceName: {{ .Chart.Name }}
            servicePort: 80
          path: /habr-demo-app(/|$)(.*)
